# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Swift
      uses: slashmo/install-swift@v0.4.0
      with:
        version: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-07-25-a
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
